// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdAaTM4okGBaNRLucUMmPrDQ4LxiAc2Uk',
    appId: '1:651673564569:android:2b5c048f9fa836e1a98f08',
    messagingSenderId: '651673564569',
    projectId: 'marriagegate-470412',
    storageBucket: 'marriagegate-470412.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdAaTM4okGBaNRLucUMmPrDQ4LxiAc2Uk',
    appId: '1:651673564569:ios:placeholder',
    messagingSenderId: '651673564569',
    projectId: 'marriagegate-470412',
    storageBucket: 'marriagegate-470412.firebasestorage.app',
    iosClientId: '651673564569-ii30grkk966qn8fhbp5ikis2h2mv72kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.matrimoneyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdAaTM4okGBaNRLucUMmPrDQ4LxiAc2Uk',
    appId: '1:651673564569:macos:placeholder',
    messagingSenderId: '651673564569',
    projectId: 'marriagegate-470412',
    storageBucket: 'marriagegate-470412.firebasestorage.app',
    iosClientId: '651673564569-ii30grkk966qn8fhbp5ikis2h2mv72kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.matrimoneyApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdAaTM4okGBaNRLucUMmPrDQ4LxiAc2Uk',
    appId: '1:651673564569:web:placeholder',
    messagingSenderId: '651673564569',
    projectId: 'marriagegate-470412',
    storageBucket: 'marriagegate-470412.firebasestorage.app',
    authDomain: 'marriagegate-470412.firebaseapp.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdAaTM4okGBaNRLucUMmPrDQ4LxiAc2Uk',
    appId: '1:651673564569:windows:placeholder',
    messagingSenderId: '651673564569',
    projectId: 'marriagegate-470412',
    storageBucket: 'marriagegate-470412.firebasestorage.app',
  );
}
